netbox_gcore_plugin/urls.py
"""URL definitions"""

from django.urls import path
from netbox.views.generic import ObjectChangeLogView
from . import models, views


urlpatterns = (
    # ZoneAccount
    path(
        "dns/accounts/",
        views.ZoneAccountListView.as_view(),
        name="zoneaccount_list",
    ),
    path(
        "dns/accounts/add/",
        views.ZoneAccountAddView.as_view(),
        name="zoneaccount_add",
    ),
    path(
        "dns/accounts/delete/",
        views.ZoneAccountBulkDeleteView.as_view(),
        name="zoneaccount_bulk_delete",
    ),
    path(
        "dns/accounts/<int:pk>/",
        views.ZoneAccountView.as_view(),
        name="zoneaccount",
    ),
    path(
        "dns/accounts/<int:pk>/delete/",
        views.ZoneAccountDeleteView.as_view(),
        name="zoneaccount_delete",
    ),
    path(
        "dns/accounts/<int:pk>/changelog/",
        ObjectChangeLogView.as_view(),
        name="zoneaccount_changelog",
        kwargs={"model": models.ZoneAccount},
    ),
    # ZoneDNS
    path(
        "dns/zones/",
        views.ZoneZonesListView.as_view(),
        name="zonezones_list",
    ),
    path(
        "dns/zones/add/",
        views.ZoneZonesAddView.as_view(),
        name="zonezones_add",
    ),
    path(
        "dns/zones/delete/",
        views.ZoneZonesBulkDeleteView.as_view(),
        name="zonezones_bulk_delete",
    ),
    path(
        "dns/zones/<int:pk>/",
        views.ZoneZonesView.as_view(),
        name="zonezones",
    ),
    path(
        "dns/zones/<int:pk>/delete/",
        views.ZoneZonesDeleteView.as_view(),
        name="zonezones_delete",
    ),
    path(
        "dns/zones/<int:pk>/changelog/",
        ObjectChangeLogView.as_view(),
        name="zonezones_changelog",
        kwargs={"model": models.ZoneZones},
    ),
    # DnsRecord
    path(
        "dns/records/",
        views.DnsRecordListView.as_view(),
        name="dnsrecord_list",
    ),
    path(
        "dns/records/add/",
        views.DnsRecordAddView.as_view(),
        name="dnsrecord_add",
    ),
    path(
        "dns/records/delete/",
        views.DnsRecordBulkDeleteView.as_view(),
        name="dnsrecord_bulk_delete",
    ),
    path(
        "dns/records/<int:pk>/",
        views.DnsRecordView.as_view(),
        name="dnsrecord",
    ),
    path(
        "dns/records/<int:pk>/delete/",
        views.DnsRecordDeleteView.as_view(),
        name="dnsrecord_delete",
    ),
    path(
        "dns/records/<int:pk>/changelog/",
        ObjectChangeLogView.as_view(),
        name="dnsrecord_changelog",
        kwargs={"model": models.DnsRecord},
    ),
)

netbox_gcore_plugin/models.py
"""Gcore Plugin Models definitions"""

from django.db import models
from django.urls import reverse
from django.core.validators import (
    MinLengthValidator,
    MaxLengthValidator,
    MinValueValidator,
    MaxValueValidator,
)
from taggit.managers import TaggableManager
from netbox.models import NetBoxModel

class ZoneAccount(NetBoxModel):
    """GCore account definition class"""

    name = models.CharField(
        max_length=255,
        null=False,
        blank=False,
        validators=[
            MinLengthValidator(limit_value=1),
            MaxLengthValidator(limit_value=255),
        ],
    )

    token = models.CharField(
        max_length=255,
        null=False,
        blank=False,
        validators=[
            MinLengthValidator(limit_value=1),
            MaxLengthValidator(limit_value=255),
        ],
    )

    tags = TaggableManager(
        through="extras.TaggedItem", related_name="netbox_gcore_plugin_zoneaccount_set"
    )

    class Meta:
        """GCore zone account Model Meta Class"""

        ordering = ("name",)

    def __str__(self):
        return f"{self.name}"

    def get_absolute_url(self):
        """override"""
        return reverse("plugins:netbox_gcore_plugin:zoneaccount", args=[self.pk])


class ZoneZones(NetBoxModel):
    """GCore DNS zone definition class"""

    account = models.ForeignKey(
        ZoneAccount, on_delete=models.CASCADE, related_name="zones"
    )

    zone_name = models.CharField(
        unique=True,
        max_length=255,
        null=False,
        blank=False,
        validators=[
            MinLengthValidator(limit_value=1),
            MaxLengthValidator(limit_value=255),
        ],
    )

    tags = TaggableManager(
        through="extras.TaggedItem", related_name="netbox_gcore_plugin_zonezones_set"
    )

    class Meta:
        """GCore DNS zone Model Meta Class"""

        ordering = ("zone_name",)

    def __str__(self):
        return f"{self.zone_name}"

    def get_absolute_url(self):
        """override"""
        return reverse("plugins:netbox_gcore_plugin:zonezones", args=[self.pk])


class DnsRecord(NetBoxModel):
    """DNS entry definition class"""

    CNAME = "CNAME"
    A = "A"

    TYPE_CHOICE = (
        (A, A),
        (CNAME, CNAME),
    )

    zone = models.ForeignKey(
        ZoneZones, on_delete=models.CASCADE, related_name="records"
    )
    record_id = name = models.CharField(
        max_length=32,
        null=False,
        blank=False,
        validators=[
            MinLengthValidator(limit_value=1),
            MaxLengthValidator(limit_value=32),
        ],
    )
    name = models.CharField(
        max_length=255,
        null=False,
        blank=False,
        validators=[
            MinLengthValidator(limit_value=1),
            MaxLengthValidator(limit_value=255),
        ],
    )
    type = models.CharField(
        max_length=64,
        choices=TYPE_CHOICE,
        default=CNAME,
        null=False,
        blank=False,
    )
    content = models.CharField(
        max_length=255,
        null=False,
        blank=False,
        validators=[
            MinLengthValidator(limit_value=1),
            MaxLengthValidator(limit_value=255),
        ],
    )
    ttl = models.IntegerField(
        default=3600,
        null=False,
        blank=False,
        validators=[
            MinValueValidator(limit_value=60),
            MaxValueValidator(limit_value=86400),
        ],
    )
    proxied = models.BooleanField(default=False, null=False, blank=False)
    tags = TaggableManager(
        through="extras.TaggedItem", related_name="netbox_gcore_plugin_dnsrecord_set"
    )

    class Meta:
        """DNS entry Meta Class"""

        ordering = (
            "zone",
            "name",
            "type",
        )
        constraints = (
            models.UniqueConstraint(
                fields=["zone", "name"],
                name="%(app_label)s_%(class)s_unique_zone_name_type_content",
            ),
        )

    def __str__(self):
        return f"{self.name} {self.type} {self.content} {self.ttl}"

    def get_absolute_url(self):
        """override"""
        return reverse("plugins:netbox_gcore_plugin:dnsrecord", args=[self.pk])

netbox_gcore_plugin/templates/netbox_gcore_plugin/dnsrecord.html
{% extends 'netbox_gcore_plugin/no_edit_base.html' %}

{% load plugins %}

{% block content %}
<div class="row mb-3">
  <div class="col col-md-6">
    <div class="card">
      <h5 class="card-header">DNS RECORD</h5>
      <div class="card-body">
        <table class="table table-hover attr-table">
            <tr>
                <th scope="row">Zone</th>
                <td>{{ object.zone|linkify }}</td>
              </tr>
          <tr>
            <th scope="row">Name</th>
            <td>{{ object.name }}</td>
          </tr>
          <tr>
            <th scope="row">Type</th>
            <td>{{ object.get_type_display }}</td>
          </tr>
          <tr>
            <th scope="row">Content</th>
            <td>{{ object.content }}</td>
          </tr>
          <tr>
            <th scope="row">TTL</th>
            <td>{{ object.ttl }}</td>
          </tr>
          <tr>
            <th scope="row">Proxied</th>
            <td>{% checkmark object.proxied %}</td>
          </tr>
          <tr>
            <th scope="row">Record ID</th>
            <td>{{ object.record_id }}</td>
          </tr>
        </table>
      </div>
    </div>
    {% include 'inc/panels/custom_fields.html' %}
    {% include 'inc/panels/tags.html' %}
    {% plugin_left_page object %}
  </div>
</div>
{% endblock content %}

netbox_gcore_plugin/templates/netbox_gcore_plugin/no_edit_base.html
{% extends 'generic/object.html' %}

{% load buttons %}
{% load custom_links %}
{% load perms %}
{% load plugins %}

{% block controls %}
  <div class="btn-list justify-content-end mb-2">
    {% plugin_buttons object %}

    {# Add/edit/delete/etc. buttons #}
    {% block control-buttons %}

      {# Default buttons #}
      {% if perms.extras.add_bookmark and object.bookmarks %}
        {% bookmark_button object %}
      {% endif %}
      {% if request.user|can_add:object %}
        {% clone_button object %}
      {% endif %}
      {% if request.user|can_delete:object %}
        {% delete_button object %}
      {% endif %}
    {% endblock control-buttons %}
  </div>

  {# Custom links #}
  <div class="d-flex justify-content-end">
    <div class="btn-list">
      {% block custom-links %}
        {% custom_links object %}
      {% endblock custom-links %}
    </div>
  </div>
{% endblock controls %}

netbox_gcore_plugin/templates/netbox_gcore_plugin/zoneaccount.html
{% extends 'netbox_gcore_plugin/no_edit_base.html' %}

{% load plugins %}

{% block content %}
<div class="row mb-3">
  <div class="col col-md-6">
    <div class="card">
      <h5 class="card-header">ZONE ACCOUNT</h5>
      <div class="card-body">
        <table class="table table-hover attr-table">
          <tr>
            <th scope="row">Zone Name</th>
            <td>{{ object.zone_name }}</td>
          </tr>
          <tr>
            <th scope="row">Token</th>
            <td>{{ object.token }}</td>
          </tr>
        </table>
      </div>
    </div>
    {% include 'inc/panels/custom_fields.html' %}
    {% include 'inc/panels/tags.html' %}
    {% plugin_left_page object %}
  </div>
</div>
{% endblock content %}

netbox_gcore_plugin/templates/netbox_gcore_plugin/zonezones.html
{% extends 'netbox_gcore_plugin/no_edit_base.html' %}

{% load plugins %}

{% block content %}
<div class="row mb-3">
  <div class="col col-md-6">
    <div class="card">
      <h5 class="card-header">DNS ZONES</h5>
      <div class="card-body">
        <table class="table table-hover attr-table">
            <tr>
                <th scope="row">Account</th>
                <td>{{ object.account|linkify }}</td>
            </tr>
          <tr>
            <th scope="row">Name</th>
            <td>{{ object.zone_name }}</td>
          </tr>
        </table>
      </div>
    </div>
    {% include 'inc/panels/custom_fields.html' %}
    {% include 'inc/panels/tags.html' %}
    {% plugin_left_page object %}
  </div>
</div>
{% endblock content %}